//S5.1

SELECT *
FROM (SELECT CP.NOMBRE AS NOMBRE, COUNT(*) AS TOTAL
FROM MF.LLAMADA LL INNER JOIN MF.TELEFONO TLF ON TLF.NUMERO=LL.TF_ORIGEN
INNER JOIN MF.COMPAÑIA CP ON TLF.COMPAÑIA=CP.CIF
WHERE TO_CHAR(LL.FECHA_HORA,'DD/MM/YY')='16/10/06'
GROUP BY CP.NOMBRE
ORDER BY TOTAL DESC)
WHERE ROWNUM=1;



//S5.2

SELECT T.NUMERO,C.NOMBRE
FROM MF.TELEFONO T INNER JOIN MF.CLIENTE C ON T.CLIENTE=C.DNI
WHERE T.NUMERO <> '654345345' AND
NOT EXISTS(SELECT L.TF_DESTINO
FROM MF.LLAMADA L
WHERE L.TF_ORIGEN='654345345' AND TO_CHAR(L.FECHA_HORA,'MM/YY')='10/06'
AND NOT EXISTS(SELECT *
FROM MF.LLAMADA L2
WHERE L2.TF_ORIGEN=T.NUMERO AND L2.TF_DESTINO=L.TF_DESTINO));


//S5.3

SELECT CLI.NOMBRE AS NOMBRE,CP.NOMBRE AS NOMBRECOMP, SUM(LL.DURACION/60 * TF.COSTE) AS COSTE
FROM MF.CLIENTE CLI INNER JOIN MF.TELEFONO TLF ON TLF.CLIENTE=CLI.DNI
INNER JOIN MF.LLAMADA LL ON LL.TF_ORIGEN=TLF.NUMERO
INNER JOIN MF.TARIFA TF ON TF.COMPAÑIA=TLF.COMPAÑIA AND TF.TARIFA=TLF.TARIFA
INNER JOIN MF.COMPAÑIA CP ON TLF.COMPAÑIA=CP.CIF
GROUP BY CLI.NOMBRE,CP.NOMBRE
ORDER BY CLI.NOMBRE DESC,CP.NOMBRE ASC;



//S5.4
SELECT SUM(DURACION) AS SUMA
FROM MF.LLAMADA LL INNER JOIN MF.TELEFONO TLF ON TLF.NUMERO=LL.TF_ORIGEN
INNER JOIN MF.CLIENTE CLI ON TLF.CLIENTE=CLI.DNI
INNER JOIN MF.TELEFONO TLF2 ON TLF2.NUMERO=LL.TF_DESTINO
INNER JOIN MF.CLIENTE CLI2 ON TLF2.CLIENTE=CLI2.DNI
WHERE CLI.PROVINCIA='La Coruña' AND CLI2.PROVINCIA= 'Jaén';


//S5.5

SELECT CLI.NOMBRE AS NOMBRE, COUNT(*) AS TOTAL
FROM MF.LLAMADA LL INNER JOIN MF.TELEFONO TLF ON TLF.NUMERO=LL.TF_ORIGEN
INNER JOIN MF.CLIENTE CLI ON TLF.CLIENTE=CLI.DNI
GROUP BY CLI.NOMBRE
HAVING COUNT(*)>5;



//S5.6

SELECT CLI.NOMBRE
FROM MF.CLIENTE CLI
INNER JOIN MF.TELEFONO TLF ON TLF.CLIENTE=CLI.DNI
INNER JOIN MF.TARIFA TF ON TF.COMPAÑIA=TLF.COMPAÑIA AND TF.TARIFA=TLF.TARIFA
GROUP BY CLI.NOMBRE
HAVING AVG(TF.COSTE) > (
SELECT AVG(COSTE)
FROM MF.TARIFA);



//S5.7
SELECT CLI.NOMBRE AS NOMBRE, SUM(TF.COSTE) AS COSTE
FROM ((((MF.LLAMADA LL INNER JOIN MF.TELEFONO TLF ON LL.TF_ORIGEN=TLF.NUMERO)
INNER JOIN MF.CLIENTE CLI ON TLF.CLIENTE=CLI.DNI)
INNER JOIN MF.COMPAÑIA CP ON TLF.COMPAÑIA=CP.CIF)
INNER JOIN MF.TARIFA TF USING (TARIFA,COMPAÑIA))
INNER JOIN MF.LLAMADA LL2 INNER JOIN MF.TELEFONO TLF2 ON LL2.TF_DESTINO=TLF2.NUMERO
INNER JOIN MF.CLIENTE CLI2 ON TLF2.CLIENTE=CLI2.DNI
INNER JOIN MF.COMPAÑIA CP2 ON TLF2.COMPAÑIA=CP2.CIF
GROUP BY CLI.NOMBRE
HAVING SUM(TF.COSTE)<100;
