//S4.1
SELECT CLI.nombre
FROM mf.CLIENTE CLI 
WHERE EXISTS
(SELECT *
FROM mf.LLAMADA INNER JOIN mf.TELEFONO ON LLAMADA.tf_origen=TELEFONO.numero
WHERE TELEFONO.cliente=CLI.dni AND TO_CHAR(LLAMADA.fecha_hora,'DD/MM/YY')='16/10/06');

//S4.2
SELECT CLI.nombre
FROM mf.CLIENTE CLI
WHERE EXISTS(
SELECT *
FROM mf.LLAMADA INNER JOIN mf.TELEFONO ON LLAMADA.tf_origen=TELEFONO.numero
WHERE TELEFONO.cliente=CLI.dni AND LLAMADA.duracion < 90);



//S4.3
SELECT CLI.nombre
FROM mf.CLIENTE CLI INNER JOIN mf.TELEFONO TLF ON TLF.cliente=CLI.dni
INNER JOIN mf.COMPAÑIA CP ON CP.cif=TLF.compañia
WHERE CP.nombre='Kietostar' AND NOT EXISTS(
SELECT *
FROM mf.LLAMADA LL
WHERE LL.tf_origen=TLF.numero AND EXTRACT(month from LL.fecha_hora) = 9);

//S4.4
SELECT*
FROM  mf.TELEFONO TLF
WHERE EXISTS(
SELECT *
FROM mf.LLAMADA LL
WHERE LL.tf_origen=TLF.numero AND LL.tf_destino='654234234')
AND NOT EXISTS(
SELECT *
FROM mf.LLAMADA LL
WHERE LL.tf_origen=TLF.numero AND LL.tf_destino='666789789');



//S4.5
SELECT CLI.nombre, TLF.numero
FROM mf.CLIENTE CLI INNER JOIN mf.TELEFONO TLF ON CLI.dni=TLF.cliente
INNER JOIN mf.COMPAÑIA CP ON CP.cif=TLF.compañia
WHERE CP.nombre='Kietostar' AND NOT EXISTS(
SELECT *
FROM mf.LLAMADA LL INNER JOIN mf.TELEFONO TLF2 ON LL.tf_destino=TLF2.numero
WHERE LL.tf_origen=TLF.numero AND TLF2.compañia=TLF.compañia);